version: '3.8'

services:
  resources-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - resources-data:/var/lib/postgresql/data

  booking-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - booking-data:/var/lib/postgresql/data

volumes:
  resources-data:
    driver: local

  booking-data:
    driver: local